package user_interface.reports;

import controllers.ManejadorVentanaReportes;
import java.awt.Color;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTable;
import models.token.Token;

/**
 * Clase que se encarga de mostrar los reportes de la app.
 *
 * @author Manu
 */
public class VentanaReportes extends javax.swing.JFrame {

    private List<Token> tokens;
    private ManejadorVentanaReportes manejador;
    private TipoReporte tipoReporte;

    /**
     * Constructor de la ventana de reportes.
     *
     * @param tokens Los tokens que se van a listar en el reporte.
     * @param tipoReporte El tipo de reporte que se desea mostrar.
     */
    public VentanaReportes(List<Token> tokens, TipoReporte tipoReporte) {
        initComponents();
        setVisible(true);
        setResizable(false);
        setLocationRelativeTo(null);
        this.tokens = tokens;
        this.tipoReporte = tipoReporte;
        this.manejador = new ManejadorVentanaReportes(this);
        manejador.setTituloLabel();
        manejador.actualizarTabla();
        cambiarAspecto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReports = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        botonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reporte");

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setText("Reporte de Tokens");
        getContentPane().add(labelTitulo, java.awt.BorderLayout.NORTH);

        jScrollPane1.setBackground(new java.awt.Color(50, 50, 50));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        tablaReports.setBackground(new java.awt.Color(40, 40, 40));
        tablaReports.setForeground(new java.awt.Color(255, 255, 255));
        tablaReports.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tablaReports);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(50, 50, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 50));

        botonSalir.setBackground(new java.awt.Color(9, 124, 233));
        botonSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir.setText("Regresar");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(botonSalir);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTable tablaReports;
    // End of variables declaration//GEN-END:variables

    /**
     * Método para obtener los tokens de esta ventana.
     *
     * @return La lista de tokens que se mostraran en la ventana.
     */
    public List<Token> getTokens() {
        return tokens;
    }

    /**
     * Método para obtener la tabla del frame, en la cual se mostraran los
     * datos.
     *
     * @return La tabla del frame.
     */
    public JTable getTablaReports() {
        return tablaReports;
    }

    /**
     * Método para obtener el tipo de reporte que se quiere mostrar en el frame.
     *
     * @return El tipo de reporte que se quiere mostrar en el frame.
     */

    public TipoReporte getTipoReporte() {
        return tipoReporte;
    }

    /**
     * Método para obtener el label que contiene el titulo del reporte que se
     * esta presentando.
     *
     * @return El label donde se mostrará el titulo del reporte.
     */

    public JLabel getLabelTitulo() {
        return labelTitulo;
    }

    /**
     * Método que se encarga de cambiar el aspecto de la ventana reportes.
     */
    private void cambiarAspecto() {
        this.getContentPane().setBackground(new Color(40, 40, 40));
        jScrollPane1.getViewport().setBackground(new Color(40, 40, 40));
        tablaReports.getTableHeader().setBackground(new Color(30, 30, 30));
        tablaReports.getTableHeader().setBackground(new Color(30, 30, 30));
        tablaReports.getTableHeader().setForeground(Color.white);
        this.setIconImage(new ImageIcon(getClass().getResource("/images/filtro.png")).getImage());
    }

}
